Added docs/reference directory.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9444,7 +9444,7 @@ else
   HAVE_SGML2HTML_FALSE=
 fi
 
-ac_config_files="$ac_config_files Makefile gdkglext.pc gtkglext.pc gdkglext-uninstalled.pc gtkglext-uninstalled.pc gdk/Makefile gdk/x11/Makefile gdk/win32/Makefile gtk/Makefile examples/Makefile docs/Makefile"
+ac_config_files="$ac_config_files Makefile gdkglext.pc gtkglext.pc gdkglext-uninstalled.pc gtkglext-uninstalled.pc gdk/Makefile gdk/x11/Makefile gdk/win32/Makefile gtk/Makefile examples/Makefile docs/Makefile docs/reference/Makefile docs/reference/gdkglext/Makefile docs/reference/gtkglext/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -9859,9 +9859,12 @@ do
   "gtk/Makefile" ) CONFIG_FILES="$CONFIG_FILES gtk/Makefile" ;;
   "examples/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/Makefile" ;;
   "docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/Makefile" ;;
+  "docs/reference/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/reference/Makefile" ;;
+  "docs/reference/gdkglext/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/reference/gdkglext/Makefile" ;;
+  "docs/reference/gtkglext/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/reference/gtkglext/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:9864: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:9867: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -10173,7 +10176,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:10176: creating $ac_file" >&5
+    { echo "$as_me:10179: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -10191,7 +10194,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:10194: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:10197: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -10204,7 +10207,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:10207: error: cannot find input file: $f" >&5
+           { { echo "$as_me:10210: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -10265,7 +10268,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:10268: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:10271: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -10276,7 +10279,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:10279: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:10282: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -10289,7 +10292,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:10292: error: cannot find input file: $f" >&5
+           { { echo "$as_me:10295: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -10406,7 +10409,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:10409: $ac_file is unchanged" >&5
+      { echo "$as_me:10412: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
