Added gdk/glext/* to dist.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10722,7 +10722,7 @@ else
   HAVE_SGML2HTML_FALSE=
 fi
 
-ac_config_files="$ac_config_files Makefile gdkglext.pc gtkglext.pc gdkglext-uninstalled.pc gtkglext-uninstalled.pc gtkglext.spec gdk/Makefile gdk/gdkglversion.h gdk/x11/Makefile gdk/win32/Makefile gtk/Makefile gtk/gtkglversion.h examples/Makefile docs/Makefile docs/reference/Makefile docs/reference/gtkglext/Makefile"
+ac_config_files="$ac_config_files Makefile gdkglext.pc gtkglext.pc gdkglext-uninstalled.pc gtkglext-uninstalled.pc gtkglext.spec gdk/Makefile gdk/gdkglversion.h gdk/x11/Makefile gdk/win32/Makefile gdk/glext/Makefile gtk/Makefile gtk/gtkglversion.h examples/Makefile docs/Makefile docs/reference/Makefile docs/reference/gtkglext/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -11136,6 +11136,7 @@ do
   "gdk/gdkglversion.h" ) CONFIG_FILES="$CONFIG_FILES gdk/gdkglversion.h" ;;
   "gdk/x11/Makefile" ) CONFIG_FILES="$CONFIG_FILES gdk/x11/Makefile" ;;
   "gdk/win32/Makefile" ) CONFIG_FILES="$CONFIG_FILES gdk/win32/Makefile" ;;
+  "gdk/glext/Makefile" ) CONFIG_FILES="$CONFIG_FILES gdk/glext/Makefile" ;;
   "gtk/Makefile" ) CONFIG_FILES="$CONFIG_FILES gtk/Makefile" ;;
   "gtk/gtkglversion.h" ) CONFIG_FILES="$CONFIG_FILES gtk/gtkglversion.h" ;;
   "examples/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/Makefile" ;;
@@ -11144,7 +11145,7 @@ do
   "docs/reference/gtkglext/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/reference/gtkglext/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:11147: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:11148: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -11462,7 +11463,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:11465: creating $ac_file" >&5
+    { echo "$as_me:11466: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -11480,7 +11481,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:11483: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:11484: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -11493,7 +11494,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:11496: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11497: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -11554,7 +11555,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:11557: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:11558: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -11565,7 +11566,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:11568: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:11569: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -11578,7 +11579,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:11581: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11582: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -11695,7 +11696,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:11698: $ac_file is unchanged" >&5
+      { echo "$as_me:11699: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
