Documentations.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10829,7 +10829,7 @@ fi
 # Output
 ##################################################
 
-ac_config_files="$ac_config_files Makefile gdkglext.pc gtkglext.pc gdkglext-uninstalled.pc gtkglext-uninstalled.pc gtkglext.spec gdk/Makefile gdk/gdkglversion.h gdk/GL/Makefile gdk/x11/Makefile gdk/win32/Makefile gtk/Makefile gtk/gtkglversion.h examples/Makefile docs/Makefile docs/reference/Makefile docs/reference/gtkglext/Makefile"
+ac_config_files="$ac_config_files Makefile gdkglext.pc gtkglext.pc gdkglext-uninstalled.pc gtkglext-uninstalled.pc gtkglext.spec gdk/Makefile gdk/gdkglversion.h gdk/GL/Makefile gdk/x11/Makefile gdk/win32/Makefile gtk/Makefile gtk/gtkglversion.h examples/Makefile docs/Makefile docs/reference/Makefile docs/reference/gtkglext/Makefile docs/reference/gtkglext/version.xml"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -11250,9 +11250,10 @@ do
   "docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/Makefile" ;;
   "docs/reference/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/reference/Makefile" ;;
   "docs/reference/gtkglext/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/reference/gtkglext/Makefile" ;;
+  "docs/reference/gtkglext/version.xml" ) CONFIG_FILES="$CONFIG_FILES docs/reference/gtkglext/version.xml" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:11255: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:11256: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -11570,7 +11571,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:11573: creating $ac_file" >&5
+    { echo "$as_me:11574: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -11588,7 +11589,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:11591: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:11592: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -11601,7 +11602,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:11604: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11605: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -11662,7 +11663,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:11665: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:11666: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -11673,7 +11674,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:11676: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:11677: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -11686,7 +11687,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:11689: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11690: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -11803,7 +11804,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:11806: $ac_file is unchanged" >&5
+      { echo "$as_me:11807: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
